<?php

namespace Entities\Repositories;

/**
 * Repositories/StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;
class StudentRepository extends EntityRepository
{
    public function getAllStudent()
    {
        $query = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('a')
            ->from('Entities\Student','a')
            ->where('a.id>=1')
            ->getQuery()
            ->execute();

        return $query;
    }
}
